Inject attribute fabrics handling
skbkontur/GroboContainer.NUnitExtensions pull request #1
Opened 2019-08-08 15:51 UTC by Umqra

This PR extends functionality of `[Injected]` attribute with support of `Func<>` fabrics. Example usage:
```C#
[Injected]
private Func<string, IDependency> dependencyFactory;
````
You can find more examples in tests: InjectedAttribute_TestFactories.cs

2019-08-08 20:18 UTC, AndrewKostousov requested changes

2019-08-08 20:18 UTC, AndrewKostousov commented on GroboContainer.NUnitExtensions/Impl/GroboTestAction.cs
> +                if (supportedFactoryFuncTypes.Contains(genericFieldType))
Я думаю, лучше со всеми вариантами `Func<,,,,,T>` тут разобраться. И если количество параметров-типов больше 4-х, кинуть исключение на тему того, что жирный фанк не поддерживается.

2019-08-09 05:59 UTC, fakefeik approved these changes

2019-08-09 06:08 UTC, AndrewKostousov commented on GroboContainer.NUnitExtensions/Impl/GroboTestAction.cs
> +                if (supportedFactoryFuncTypes.Contains(genericFieldType))
Теперь хочу тест на эту ошибку, если это не сложно :-)

2019-08-09 06:31 UTC, AndrewKostousov approved these changes

2019-08-09 06:32 UTC, merged