Async SetUp support
skbkontur/GroboContainer.NUnitExtensions pull request #2
Opened 2019-08-18 12:15 UTC by mr146

2019-08-19 13:31 UTC, AndrewKostousov requested changes

2019-08-19 13:31 UTC, AndrewKostousov commented on GroboContainer.NUnitExtensions/Impl/GroboTestAction.cs
> +                if(wrapperMethod.ReturnType == typeof(Task))
Пробельчик забыл после слова `if`.

2019-08-19 13:31 UTC, AndrewKostousov commented on GroboContainer.NUnitExtensions.Tests/ExecutionOrder/AsyncGroboTestFixture_Test.cs
> +        public void Test01()
Тебе ведь асинхронные сетапы не сами по себе нужны, а для написания асинхронных тестов, так? Предлагаю тогда и тут тесты асинхронными сделать.

2019-08-19 17:02 UTC, mr146 commented on GroboContainer.NUnitExtensions/Impl/GroboTestAction.cs
> +                if(wrapperMethod.ReturnType == typeof(Task))
Поправил.

2019-08-19 17:02 UTC, mr146 commented on GroboContainer.NUnitExtensions.Tests/ExecutionOrder/AsyncGroboTestFixture_Test.cs
> +        public void Test01()
Все так, поправил.

2019-08-20 07:13 UTC, AndrewKostousov approved these changes

2019-08-20 07:14 UTC, merged