Support properties injection
skbkontur/GroboContainer.NUnitExtensions pull request #3
Opened 2019-08-20 05:47 UTC by mr146

2019-08-20 07:25 UTC, AndrewKostousov requested changes

2019-08-20 07:25 UTC, AndrewKostousov commented on GroboContainer.NUnitExtensions.Tests/Container/InjectedAttributeTestBase.cs
> +        private IServiceWithNoDependencies ProtectedPropertyInBaseClass { get; set; }
Пропертя называется Protected, но ничем не отличается от PrivatePropertyInBaseClass. И обращений к ней, насколько я вижу нет. Забыл тест добавить?

2019-08-20 07:25 UTC, AndrewKostousov commented on GroboContainer.NUnitExtensions/Impl/GroboTestAction.cs
> +                throw new InvalidOperationException($"Unable to instantiate injected field '{propertyInfo.Name}' of delegate type '{propertyType}'. " +
field -> property

Или даже лучше отрефакторить методы инстанцирования полей и свойств, так чтобы логика `if (typeof(Delegate).IsAssignableFrom(propertyType))` и обращение к контейнеру были в одном экземпляре - выделить метод `InstantiateFieldOrProperty`.

2019-08-20 17:03 UTC, mr146 commented on GroboContainer.NUnitExtensions/Impl/GroboTestAction.cs
> +                throw new InvalidOperationException($"Unable to instantiate injected field '{propertyInfo.Name}' of delegate type '{propertyType}'. " +
И правда что, выделил `InstantiateMember`.

2019-08-20 17:03 UTC, mr146 commented on GroboContainer.NUnitExtensions.Tests/Container/InjectedAttributeTestBase.cs
> +        private IServiceWithNoDependencies ProtectedPropertyInBaseClass { get; set; }
Забыл, поправил.

2019-08-21 08:14 UTC, AndrewKostousov approved these changes

2019-08-21 09:02 UTC, merged